package it.fi.itismeucci.delaCruz;


import java.awt.event.KeyEvent;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author darda
 */
public class ClientChatGUI extends javax.swing.JFrame {

    public String nomeUser;
    
    /**
     * Creates new form ClientChatGUI
     */
    public ClientChatGUI(String nomeUser) {
        super("Chat Online");
        initComponents();
        
        setResizable(false);
        this.nomeUser = nomeUser;
        setLocationRelativeTo(null);
        textAreaChat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaChat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textFieldChat = new javax.swing.JTextField();
        buttonInvia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaChat.setColumns(20);
        textAreaChat.setRows(5);
        jScrollPane1.setViewportView(textAreaChat);

        jLabel1.setText("Chat Online - Per chattare con gli amici");

        textFieldChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldChatActionPerformed(evt);
            }
        });
        textFieldChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldChatKeyPressed(evt);
            }
        });

        buttonInvia.setText("Invia");
        buttonInvia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonInviaMouseClicked(evt);
            }
        });
        buttonInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textFieldChat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonInvia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInvia))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInviaActionPerformed

    private void textFieldChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldChatActionPerformed

    private void buttonInviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonInviaMouseClicked
        inviaMessaggioInChat();
    }//GEN-LAST:event_buttonInviaMouseClicked
    
    private void textFieldChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldChatKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            inviaMessaggioInChat();
        }
    }//GEN-LAST:event_textFieldChatKeyPressed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInvia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaChat;
    private javax.swing.JTextField textFieldChat;
    // End of variables declaration//GEN-END:variables

    public void appendTextArea(String msg){
        textAreaChat.append(msg + '\n');
    }
    
    private void inviaMessaggioInChat(){
        riceviMessaggio(textFieldChat.getText());
        MainClient.out.invioAlServer("@"+nomeUser + " " + textFieldChat.getText());
        
        textFieldChat.setText("");
    }

    public void riceviMessaggio(String str){
        textAreaChat.append(nomeUser + ": " + str + '\n');
    }
    
    public JTextArea getTextAreaChat() {
        return textAreaChat;
    }

}
